# coding: utf-8
import os

replacements = {
    "HÃ¡c NhÃ¡jc CÃ» DÃ¢n Tá»™c": "Học Nhạc Cụ Dân Tộc",
    "ÄÃ n Tranh": "Đàn Tranh",
    "SÃ¡o TrÃºc": "Sáo Trúc",
    "ÄÃ n Báº§u": "Đàn Bầu",
    "Trá»‘ng": "Trống",
    "Chá»\x8dn Nháº¡c Cá»¥ Luyá»\x87n Táº\xadp": "Chọn Nhạc Cụ Luyện Tập",
    "Chá»\x8dn nháº¡c cá»¥ há»\x8dc táº\xadp Ä‘á»\x9f má»\x9f": "Chọn nhạc cụ học tập để mở",
    "HoÃ n thÃ nh": "Hoàn thành",
    "BÃ i há»\x8dc": "Bài học",
    "phÃºt": "phút",
    "Tuáº§n nÃ y": "Tuần này",
    "Streak": "Streak",
    "Tuáº§n": "Tuần",
    "ngÃ y": "ngày",
    "ChÆ¡i Thá»\xad": "Chơi Thử",
    "ChÆ¡i láº¡i": "Chơi lại",
    "Trá»\x9f vá»\x81": "Trở về",
    "BÃ i tiáº¿p": "Bài tiếp",
    "Thá»\xad láº¡i": "Thử lại",
    "XÃ¡c nháº\xadn": "Xác nhận",
    "Äiá»\x81n Ä‘á»§ táº¥t cáº£ Ã´ trá»\x9fng!": "Điền đầy đủ tất cả ô trống!",
    "ChÃ\xadnh xÃ¡c!": "Chính xác!",
    "ÄÃ¡p Ã¡n:": "Đáp án:",
    "CÃ¢u": "Câu",
    "tiáº¿p": "tiếp",
    "Chá»\x8dn ná»‘t nháº¡c cÃ²n thiáº¿u theo thá»\x9bi tá»±": "Chọn nốt nhạc còn thiếu theo thứ tự",
    "Chá»\x8dn ná»‘t nháº¡c cÃ²n thiáº¿u theo thá»© tá»±": "Chọn nốt nhạc còn thiếu theo thứ tự",
    "BÃ i %d / %d  â€”  Äiá»\x81n ná»‘t cÃ²n thiáº¿u": "Bài %d / %d — Điền nốt nhạc còn thiếu",
    "Chá»\x8dn ná»‘t:": "Chọn nốt:",
    "Nháº\xadn 'XÃ¡c nháº\xadn' Ä‘á»\x9f kiá»\x83m tra!": "Nhấn 'Xác nhận' để kiểm tra!",
    "HoÃ n háº£o!": "Hoàn hảo!",
    "ChÆ°a Ä‘Ãºng. Xem ná»‘t mÃ u Ä\x91á»\x8f.": "Chưa đúng. Xem nốt màu đỏ.",
    "Mini-game káº¿t thÃºc!": "Mini-game kết thúc!",
    "Chá»\x8dn nháº¡c cá»¥ sÃ¡ng Ä‘á»\x9f báº¯t Ä‘áº¥u luyá»\x87n táº\xadp.": "Chọn nhạc cụ sáng để bắt đầu luyện tập.",
    "KhÃ¡m PhÃ¡ PhÃ²ng Há»\x8dc": "Khám Phá Phòng Học",
    "Di chuyá»ƒn: WASD / PhÃ\xadm mÅ¥i tÃªn": "Di chuyển: WASD / Phím mũi tên",
    "TÆ°Æ¡ng tÃ¡c: E / Space / Cháº¡m": "Tương tác: E / Space / Chạm",
    "VÃ o PhÃ²ng Há»\x8dc": "Vào Phòng Học",
    "ÄÃ n Tranh Cơ Bản I": "Đàn Tranh Cơ Bản I",
    "The Journey | HÃ nh trÃ\xadnh Viá»\x81t Nháº\xadc": "Hành Trình Việt Nhạc",
    "Xáº¿p háº\xadn tuáº\xadn": "Xếp hạng tuần",
    "Tiáº¿p tá»¥c há»\x8dc": "Tiếp tục học",
    "Hoáº\xadt Ä‘á»\x99ng nhanh": "Hoạt động nhanh",
    "Xáº¿p háº\xadn tuáº\xadn": "Xếp hạng tuần",
    "Báº¡n": "Bạn",
    "Minh Anh": "Minh Anh",
    "Gia Báº£o": "Gia Bảo",
    "Linh Chi": "Linh Chi",
    "12 BÃ\xa0i há»\x8dc  â€¢  Tá»« cÆ¡ báº\xadn Ä‘áº¿n Tremolo": "12 Bài học • Từ cơ bản đến Tremolo",
    "8 BÃ\xa0i há»\x8dc  â€¢  HÆ¡i thá»\x9f & Ká»\x91 thuáº\xadt lÆ°á»\x9fng Ä‘Æ¡n": "8 Bài học • Hơi thở & Kỹ thuật lưỡng đơn",
    "10 BÃ\xa0i há»\x8dc  â€¢  Nháº\xadn vuá»\x91t Ä‘Æ¡n Ã¢m sáº¯c": "10 Bài học • Nhấn vuốt đơn âm sắc",
    "6 BÃ\xa0i há»\x8dc  â€¢  Trá»\x91ng há»\x9bi truyá»\x81n thá»\x91ng": "6 Bài học • Trống hội truyền thống",
    "Lá»\x91 trÃ\xadnh:": "Lộ trình:",
    "Chá»\x8dn Há»\x8dc  â†’": "Chọn Học →",
    "ÄÄƒng nháº\xadp": "Đăng nhập",
    "ÄÄƒng kÃ½": "Đăng ký",
    "TÃªn Ä‘Äƒng nháº\xadp": "Tên đăng nhập",
    "Nháº\xadp tÃªn ngÆ°á»\x8di dÃ¹ng...": "Nhập tên người dùng...",
    "Máº\xadt kháº\xadu": "Mật khẩu",
    "Hoáº\xadc tiáº¿p tá»¥c khÃ´ng cáº\xadn tÃ\xa0i khoáº\xadu:": "Hoặc tiếp tục không cần tài khoản:",
    "ChÆ¡i Thá»\xad (Guest)": "Chơi Thử (Guest)",
    "Nguyá»\x85n VÄ\x83n A...": "Nguyễn Văn A...",
    "Nháº\xadc cá»¥ yÃªu thÃ\xadch...": "Nhạc cụ yêu thích...",
    "Táº¡o tÃ\xa0i khoáº\xadn": "Tạo tài khoản",
    "Tuáº\xadn nÃ\xa0y": "Tuần này",
    "Tuáº\xadn": "Tuần",
    "ngÃ\xa0y": "ngày",
    "BÃ\xa0i há»\x8dc": "Bài học",
    "hoÃ\xa0n thÃ\xa0nh": "hoàn thành",
    "Chá»\x8dn Há»\x8dc": "Chọn Học",
    "Trá»\x9f vá»\x81": "Trở về",
    "BÃ\xa0i tiáº¿p": "Bài tiếp",
    "Thá»\xad láº¡i": "Thử lại",
    "XÃ¡c nháº\xadn": "Xác nhận",
    "Äiá»\x81n Ä‘á»§ táº¥t cáº£ Ã´ trá»\x9fng!": "Điền đầy đủ tất cả ô trống!",
    "ChÃ\xadnh xÃ¡c!": "Chính xác!",
    "ÄÃ¡p Ã¡n:": "Đáp án:",
    "CÃ¢u": "Câu",
    "tiáº¿p": "tiếp",
    "Chá»\x8dn ná»‘t nháº¡c cÃ²n thiáº¿u theo thá»© tá»±": "Chọn nốt nhạc còn thiếu theo thứ tự",
    "BÃ\xa0i %d / %d  â€”  Äiá»\x81n ná»‘t cÃ²n thiáº¿u": "Bài %d / %d — Điền nốt nhạc còn thiếu",
    "Chá»\x8dn ná»‘t:": "Chọn nốt:",
    "Nháº\xadn 'XÃ¡c nháº\xadn' Ä‘á»\x83 kiá»\x83m tra!": "Nhấn 'Xác nhận' để kiểm tra!",
    "HoÃ\xa0n háº£o!": "Hoàn hảo!",
    "ChÆ°a Ä‘Ãºng. Xem ná»‘t mÃ u Ä‘á»\x8f.": "Chưa đúng. Xem nốt màu đỏ.",
    "Mini-game káº¿t thÃºc!": "Mini-game kết thúc!",
    "Chá»\x8dn nháº¡c cá»¥ sÃ¡ng Ä‘á»\x83 báº¯t Ä‘áº§u luyá»\x87n táº\xadp.": "Chọn nhạc cụ sáng để bắt đầu luyện tập.",
    "KhÃ¡m PhÃ¡ PhÃ²ng Há»\x8dc": "Khám Phá Phòng Học",
    "Di chuyá»ƒn: WASD / PhÃ­m mÅ©i tÃªn": "Di chuyển: WASD / Phím mũi tên",
    "TÆ°Æ¡ng tÃ¡c: E / Space / Cháº¡m": "Tương tác: E / Space / Chạm",
    "VÃ o PhÃ²ng Há»\x8dc": "Vào Phòng Học",
    "ÄÃ n Tranh Cơ Bản I": "Đàn Tranh Cơ Bản I",
    "The Journey | HÃ nh trÃ¬nh Viá»‡t Nháº¡c": "Hành Trình Việt Nhạc",
    "Xáº¿p háº¡ng tuáº§n": "Xếp hạng tuần",
    "Tiáº¿p tá»¥c há»\x8dc": "Tiếp tục học",
    "Hoáº¡t Ä‘á»™ng nhanh": "Hoạt động nhanh",
    "Xáº¿p háº¡ng tuáº§n": "Xếp hạng tuần",
    "Báº¡n": "Bạn",
    "Minh Anh": "Minh Anh",
    "Gia Báº£o": "Gia Bảo",
    "Linh Chi": "Linh Chi",
    "12 BÃ i há»\x8dc  â€¢  Tá»« cÆ¡ báº§n Ä‘áº¿n Tremolo": "12 Bài học • Từ cơ bản đến Tremolo",
    "8 BÃ\i há»\x8dc  â€¢  HÆ¡i thá»\x9f & Ká»\x91 thuáº\xadt lÆ°á»\x9fng Ä‘Æ¡n": "8 Bài học • Hơi thở & Kỹ thuật lưỡng đơn",
    "10 BÃ\i há»\x8dc  â€¢  Nháº\xadn vuá»\x91t Ä‘Æ¡n Ã¢m sáº¯c": "10 Bài học • Nhấn vuốt đơn âm sắc",
    "6 BÃ\i há»\x8dc  â€¢  Trá»\x91ng há»\x9bi truyá»\x81n thá»\x91ng": "6 Bài học • Trống hội truyền thống",
    "Lá»\x91 trÃ\xadnh:": "Lộ trình:",
    "Chá»\x8dn Há»\x8dc  â†’": "Chọn Học →",
    # Additional characters
    "ÄÃ n": "Đàn",
    "BÃ i": "Bài",
    "Nháº¡c cá»¥": "Nhạc cụ",
    "Tuáº§n": "Tuần",
    "Há»\x8dc": "Học",
    "Thá»\xad": "Thử",
    "Luyá»\x87n": "Luyện",
    "khÃ´ng": "không",
    "khoáº£n": "khoản",
    "tÃ i": "tài",
    "trá»\x9fng": "trống",
    "ÄÃ´": "Đô",
    "RÃª": "Rê",
    "ká»\x91": "kỹ",
    "thá»\x9f": "thở",
    "bÃ\xa0i": "bài",
    "giáº£ng": "giảng",
    "cá»§a": "của",
    "Viá»\x81t": "Việt",
    "Nháº\xadc": "Nhạc",
    "â˜…": "★",
    "â˜†": "☆",
    "âœ“": "✓",
    "âœ—": "✗",
    "â†\x90": "←",
    "â†’": "→",
    "â–¶": "▶",
    "âœ“  XÃ¡c nháº\xadn": "✓  Xác nhận",
    "â†º Thá»\xad láº¡i": "↺ Thử lại",
    "CÃ¢u 1 / %d": "Câu 1 / %d",
    "CÃ¢u tiáº¿p  â†’": "Câu tiếp  →",
    "CÃ¢u %d / %d": "Câu %d / %d",
    "BÃ\xa0i %d / %d": "Bài %d / %d",
    "Chá»\x8dn ná»‘t nháº¡c cÃ²n thiáº¿u": "Chọn nốt nhạc còn thiếu",
    "Mini-game káº¿t thÃºc! ðŸŽ‰": "Mini-game kết thúc! 🎉",
    "Nháº¥n TAP hoáº·c SPACE": "Nhấn TAP hoặc SPACE",
    "vÃ¹ng sÃ¡ng": "vùng sáng",
    "Nháº¥n TAP hoáº\xadc SPACE khi ná»\x91t nháº\xadc cháº\xadm vÃ¹ng sÃ¡ng!": "Nhấn TAP hoặc SPACE khi nốt nhạc chạm vùng sáng!",
    "Báº¯t Ä‘áº§u": "Bắt đầu",
    "ngay": "ngay",
    "Challenge": "Thử thách",
    "BÃ\xa0i tiáº¿p  â†’": "Bài tiếp  →",
    "Chá»\x8dn Nháº¡c Cá»¥ Luyá»\x87n Táº\xadp": "Chọn Nhạc Cụ Luyện Tập",
    "Chá»\x8dn nháº¡c cá»¥ há»\x8dc táº\xadp Ä‘á»\x9f má»\x9f lÃ²ng": "Chọn nhạc cụ học tập để mở lộ trình",
    "Chá»\x8dn Nháº¡c Cá»¥": "Chọn Nhạc Cụ",
    "Lá»\x91 trÃ\xadnh: %d/%d hoÃ\xa0n thÃ\xa0nh": "Lộ trình: %d/%d hoàn thành",
    "Lá»\x91 trÃ\xadnh: 7/12 hoÃ\xa0n thÃ\xa0nh": "Lộ trình: 7/12 hoàn thành",
    "Lá»\x91 trÃ\xadnh: 2/8 hoÃ\xa0n thÃ\xa0nh": "Lộ trình: 2/8 hoàn thành",
    "Lá»\x91 trÃ\xadnh: 5/10 hoÃ\xa0n thÃ\xa0nh": "Lộ trình: 5/10 hoàn thành",
    "Lá»\x91 trÃ\xadnh: 3/6 hoÃ\xa0n thÃ\xa0nh": "Lộ trình: 3/6 hoàn thành",
    "Báº¡n (#8)": "Bạn (#8)",
    "Streak hÃ\xa0ng tuáº§n": "Streak hàng tuần",
    "ðŸ”¥ 6 Tuáº§n": "🔥 6 Tuần",
    "Tuáº§n nÃ\xa0y": "Tuần này",
    "Tuáº§n nÃ\xa0y": "Tuần này",
    "ÄÃ n Tranh Basics I": "Đàn Tranh Cơ Bản I",
    "The Journey | HÃ nh trÃ\xadnh Viá»\x81t Nháº¡c": "Hành Trình Việt Nhạc",
    "HoÃ\xa0n ThÃ\xa0nh! ðŸŽ‰": "Hoàn Thành! 🎉",
    "Thá»\xad láº¡i": "Thử lại",
    "BÃ\xa0i tiáº¿p": "Bài tiếp",
    "ChÆ¡i Thá»\xad (Guest)": "Chơi Thử (Guest)",
    "ðŸŽµ  VietStage Room": "🎵  VietStage Room",
    "ðŸ   Home": "🏠 Home",
    "ðŸ“Š Progress": "📊 Progress",
    "ðŸ «  KhÃ¡m PhÃ¡ PhÃ²ng Há»\x8dc": "🏫  Khám Phá Phòng Học",
    "Chá»\x8dn nháº¡c cá»¥ sÃ¡ng Ä‘á»\x9f báº¯t Ä‘áº§u luyá»\x87n táº\xadp.": "Chọn nhạc cụ sáng để bắt đầu luyện tập.",
    "ðŸŽ®  Di chuyá»ƒn: WASD / PhÃ­m mÅ©i tÃªn": "🎮  Di chuyển: WASD / Phím mũi tên",
    "âš¡  TÆ°Æ¡ng tÃ¡c: E / Space / Cháº¡m": "⚡  Tương tác: E / Space / Chạm",
    "VÃ o PhÃ²ng Há»\x8dc": "Vào Phòng Học",
    "Ná»\x91t Ä\x90Æ¡n Ä\x90Ã n Báº§u": "Nốt Đơn Đàn Bầu",
    "Ká»\x91 thuáº\xadting Nháº\xadn Vuá»\x91t": "Kỹ thuật Nhấn Vuốt",
    "Nhá»\x8b p Trá»\x91ng Há»\x9bi": "Nhịp Trống Hội",
    "Nhá»\x8bp Trá»\x91ng Há»\x9bi": "Nhịp Trống Hội",
    "Ká»\x91 thuáº\xadting": "Kỹ thuật",
    "Ká»\x91 thuáº\xadt": "Kỹ thuật",
    "Nháº\xadn Vuá»\x91t": "Nhấn Vuốt",
    "Há»\x9bi": "Hội",
    "Trá»\x91ng": "Trống",
    "ðŸŸŽµ": "🎵",
    "ðŸŽµ": "🎵",
    "ðŸŽ‹": "🎋",
    "ðŸŽ»": "🎻",
    "ðŸ¥\x81": "🥁",
    "ðŸ": "",
    "Ã¢": "â",
    "Ãª": "ê",
    "Ã´": "ô",
    "Ã¹": "ù",
    "Ãº": "ú",
    "Ã½": "ý",
    "Ã³": "ó",
    "Ã ": "à",
    "Ã¡": "á",
    "Ã£": "ã",
    "Ã\xad": "í",
    "Ã\xa0": "à",
    "Ä\x83": "ă",
    "Ä‘": "đ",
    "Ä\x90": "Đ",
    "Æ°": "ư",
    "Æ¡": "ơ",
    "áº£": "ả",
    "áº§": "ầ",
    "áº¯": "ắ",
    "áº\xad": "ậ",
    "á»\x9f": "ở",
    "á»\x91": "ố",
    "á»\x8b": "ị",
    "á»\x8d": "ọ",
    "á»\x81": "ề",
    "á»\x83": "ể",
    "á»\x93": "ồ",
    "á»\x95": "ổ",
    "á»\x99": "ộ",
    "á»\x9b": "ớ",
    "á»\x9d": "ờ",
    "á»\xa0": "ợ",
    "á»\xa3": "ợ",
    "á»\xa5": "ụ",
    "á»\xa7": "ủ",
    "á»\xab": "ừ",
    "á»\xad": "ử",
    "á»\xb1": "ự",
    "áº½": "ẽ"
}

scripts_dir = "e:/VietStageGame/scripts/ui"
for root_path, dirs, files in os.walk(scripts_dir):
    for f in files:
        if f.endswith(".gd"):
            filepath = os.path.join(root_path, f)
            print("Processing:", filepath)
            with open(filepath, "r", encoding="utf-8", errors="ignore") as file:
                content = file.read()
            
            # Perform exact key replacements
            for key, val in sorted(replacements.items(), key=lambda x: -len(x[0])):
                content = content.replace(key, val)
                
            with open(filepath, "w", encoding="utf-8") as file:
                file.write(content)

print("Done string fixes!")
